import time

print("Olá!\nSeja Bem-vindo a nossa loja!!")
nome = input("Digite seu Nome: ")
print("REGISTRANDO...")
time.sleep(2)
print("REGISTRADO")
time.sleep(0.70)
cpf = input("Digite seu CPF: ")
print("REGISTRANDO...")
time.sleep(2)
print("REGISTRADO")
time.sleep(0.70)

cond1 = input("Deseja Receber Notificações pelo seu número  de telefone?('s' PARA SIM e 'n' PARA NÃO): ").upper()
if cond1 == "S":
  nt = input("Digite o numero de telefone: ")
  print('NÚMERO REGISTRADO COM SUCESSO!!!')
elif cond1 == "N":
  print("REGISTRADO")
else:
  print("ERROR")


cond2 = str(input("Deseja ver o nosso catálogo?('s' PARA SIM e 'n' PARA NÃO): ")).upper()
if cond2 == "S":
  print("AGUARDE")
  time.sleep(3.5)
  print('\n\n')
  print("=================================================HATCH===============================================|" )
  print('\n')
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print("|              NOME: GOL              |                        |              NOME: GOL              |" )
  print("|=====================================|                        |=====================================|" )
  print("|             VERSÃO: 1.0             |                        |             VERSÃO: 1.6             |" )
  print("|=====================================|                        |=====================================|" )
  print("|  DESTAQUES: 84 cv (E) / 75 cv (G)   |                        | DESTAQUES: 104 cv (E) / 101 cv (G)  |" )
  print("| Manual de 5 velocidades Total flex  |                        | Manual de 5 velocidades Total flex  |" )
  print("|               4 portas              |                        |               4 portas              |" )
  print("|=====================================|                        |=====================================|" )
  print("|         PREÇO: R$ 61.160,00         |                        |         PREÇO: R$ 61.160,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print('\n\n')
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print("|              NOME: FOX              |                        |              NOME: FOX              |" )
  print("|=====================================|                        |=====================================|" )
  print("|          VERSÃO: Connect 1.6        |                        |          VERSÃO: Xtreme 1.6         |" )
  print("|=====================================|                        |=====================================|" )
  print("| DESTAQUES: 104 cv (E) / 101 cv (G)  |                        | DESTAQUES: 104 cv (E) / 101 cv (G)  |" )
  print("| Manual de 5 velocidades Total flex  |                        | Manual de 5 velocidades Total flex  |" )
  print("|               4 portas              |                        |               4 portas              |" )
  print("|=====================================|                        |=====================================|" )
  print("|         PREÇO: R$ 62.340,00         |                        |         PREÇO: R$ 67.990,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print('\n\n')
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print("|             NOME: POLO              |                        |             NOME: POLO              |" )
  print("|=====================================|                        |=====================================|" )
  print("|           VERSÃO: 1.0 MPI           |                        |           VERSÃO: 1.6 MSI           |" )
  print("|=====================================|                        |=====================================|" )
  print("|  DESTAQUES: 84 cv (E) / 75 cv (G)   |                        | DESTAQUES: 117 cv (E) / 110 cv (G)  |" )
  print("| Manual de 5 velocidades Total flex  |                        | Manual de 6 velocidades Total flex  |" )
  print("|               4 portas              |                        |               4 portas              |" )
  print("|=====================================|                        |=====================================|" )
  print("|         PREÇO: R$ 66.120,00         |                        |         PREÇO: R$ 78.180,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print('\n\n')
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print("|             NOME: POLO              |                        |             NOME: POLO              |" )
  print("|=====================================|                        |=====================================|" )
  print("|    VERSÃO: CONFORTLINE 200 TSI      |                        |      VERSÃO: HIGHLINE 200 TSI       |" )
  print("|=====================================|                        |=====================================|" )
  print("| DESTAQUES: 128 cv (E) / 116 cv (G)  |                        | DESTAQUES: 128 cv (E) / 116 cv (G)  |" )
  print("| Manual de 6 velocidades Total flex  |                        | Manual de 6 velocidades Total flex  |" )
  print("|               4 portas              |                        |               4 portas              |" )
  print("|=====================================|                        |=====================================|" )
  print("|         PREÇO: R$ 91.720,00         |                        |         PREÇO: R$ 98.490,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print('\n\n')
  print("|+++++++++++++++++++++++++++++++++++++|" )
  print("|             NOME: POLO              |" )
  print("|=====================================|" )
  print("|    VERSÃO: CONFORTLINE 250 TSI      |" )
  print("|=====================================|" )
  print("|          DESTAQUES: 150 cv          |" )
  print("| Manual de 6 velocidades Total flex  |" )
  print("|               4 portas              |" )
  print("|=====================================|" )
  print("|        PREÇO: R$ 120.040,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|" )
  print('\n\n')
  print("=================================================SEDAN===============================================|" )
  print('\n\n')
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print("|            NOME: VIRTUS             |                        |            NOME: VIRTUS             |" )
  print("|=====================================|                        |=====================================|" )
  print("|           VERSÃO: 1.6 MSI           |                        |    VERSÃO: CONFORTLINE 200 TSI      |" )
  print("|=====================================|                        |=====================================|" )
  print("| DESTAQUES: 117 cv (E) / 110 cv (G)  |                        | DESTAQUES: 128 cv (E) / 116 cv (G)  |" )
  print("| Manual de 5 velocidades Total flex  |                        |     Automatico de 6 velocidades     |" )
  print("|               4 portas              |                        |        Total flex 4 portas          |" )
  print("|=====================================|                        |=====================================|" )
  print("|         PREÇO: R$ 90.090,00         |                        |         PREÇO: R$ 96.000,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print('\n\n')
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )
  print("|            NOME: VIRTUS             |                        |            NOME: VIRTUS             |" )
  print("|=====================================|                        |=====================================|" )
  print("|      VERSÃO: HIGHLINE 200 TSI       |                        |           VERSÃO: 250 TSI           |" )
  print("|=====================================|                        |=====================================|" )
  print("| DESTAQUES: 128 cv (E) / 116 cv (G)  |                        |   DESTAQUES: 250 TSI / 150 cv (G)   |" )
  print("|     Automatico de 6 velocidades     |                        |     Automatico de 6 velocidades     |" )
  print("|        Total flex 4 portas          |                        |        Total flex 4 portas          |" )
  print("|=====================================|                        |=====================================|" )
  print("|        PREÇO: R$ 109.740,00         |                        |         PREÇO: R$ 125.950,00         |" )
  print("|+++++++++++++++++++++++++++++++++++++|                        |+++++++++++++++++++++++++++++++++++++|" )





else:
  print("FINALIZANDO SEÇÃO!!!")
  time.sleep(2)
  print()
